// This file will eventually be auto-generated by Supabase CLI.
// For now it's a manual stub that keeps TypeScript happy.
// Once your schema is live, run: npx supabase gen types typescript --project-id YOUR_ID > lib/database.types.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          username: string | null
          full_name: string | null
          avatar_url: string | null
          city: string | null
          bio: string | null
          xp: number
          level: string
          is_early_bird: boolean
          is_pioneer: boolean
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['profiles']['Row'], 'created_at'>
        Update: Partial<Database['public']['Tables']['profiles']['Insert']>
      }
      categories: {
        Row: {
          id: string
          name: string
          slug: string
          emoji: string
          description: string
          is_active: boolean
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['categories']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['categories']['Insert']>
      }
      brands: {
        Row: {
          id: string
          category_id: string
          name: string
          slug: string
          logo_url: string | null
          tagline: string | null
          description: string | null
          price_range: string
          origin_city: string | null
          origin_country: string
          website_url: string | null
          is_active: boolean
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['brands']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['brands']['Insert']>
      }
      comparisons: {
        Row: {
          id: string
          user_id: string
          category_id: string
          brand_a_id: string
          brand_b_id: string
          winner_id: string
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['comparisons']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['comparisons']['Insert']>
      }
      shelf_items: {
        Row: {
          id: string
          user_id: string
          brand_id: string
          category_id: string
          rank: number
          score: number
          quick_review: string | null
          tried_at: string | null
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['shelf_items']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['shelf_items']['Insert']>
      }
      user_badges: {
        Row: {
          id: string
          user_id: string
          badge_slug: string
          earned_at: string
        }
        Insert: Omit<Database['public']['Tables']['user_badges']['Row'], 'id' | 'earned_at'>
        Update: Partial<Database['public']['Tables']['user_badges']['Insert']>
      }
      cafes: {
        Row: {
          id: string
          name: string
          address: string
          city: string
          lat: number
          lng: number
          google_place_id: string | null
          avg_rating: number | null
          review_count: number
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['cafes']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['cafes']['Insert']>
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}
